module.exports = new Map([
  ['Maple Amur', 'Amur Maple'],
  ['Maple Bigleaf', 'Bigleaf Maple'],
  ['Maple Manitoba', 'Manitoba Maple'],
  ['Maple Black', 'Black Maple'],
  ['Maple Japanese', 'Japanese Maple'],
  ['Maple Striped', 'Striped Maple'],
  ['Maple Norway', 'Norway Maple'],
  ['Maple Red', 'Red Maple'],
  ['Maple Silver', 'Silver Maple'],
  ['Maple Sugar', 'Sugar Maple'],
  ['Maple Tatarian', 'Tatarian Maple'],
  ['Buckeye Ohio', 'Ohio Buckeye'],
  ['Horsechestnut Common', 'Horse-Chestnut'],
  ['Birch Yellow', 'Yellow Birch'],
  ['Birch Alaskan', 'Alaskan Birch'],
  ['Birch River', 'River Birch'],
  ['Birch White', 'White Birch'],
  ['Birch Gray', 'Gray Birch'],
  ['Birch Himalayan Whitebarked', 'Himalayan Birch'],
  ['Hickory Bitternut', 'Bitternut Hickory'],
  ['Hickory Shagbark', 'Shagbark Hickory'],
  ['Catalpa northern', 'Northern Catalpa'],
  ['Katsura tree', 'Katsura'],
  ['Redbud Eastern', 'Eastern Redbud'],
  ['Red Osier Dogwood', 'Red Osier Dogwood'],
  ['Hazel American', 'American Hazelnut'],
  ['Hazel Turkish', 'Turkish Hazel'],
  ['Smoke bush', 'European Smoketree'],
  ['Olive Russian', 'Russian Olive'],
  ['Walnut Black', 'Black Walnut'],
  ['Wahoo Tree', 'American Wahoo'],
  ['Beech American', 'American Beech'],
  ['Beech Blue', 'Blue Beech'],
  ['Beech European', 'European Beech'],
  ['Ash White', 'White Ash'],
  ['Ash European', 'European Ash'],
  ['Ash Black', 'Black Ash'],
  ['Ash Green', 'Green Ash'],
  ['Ginkgo', 'Ginkgo'],
  ['Locust Honey', 'Honey Locust'],
  ['Coffeetree Kentucky', 'Kentucky Coffeetree'],
  ['Butternut', 'Butternut'],
  ['Goldenchain Tree', 'Golden Chain'],
  ['Tulip-tree', 'Tulip Tree'],
  ['Amur Corktree', 'Amur Cork Tree'],
  ['Sycamore American', 'American Sycamore'],
  ['Poplar Silver/White', 'White Poplar'],
  ['Poplar Balsam', 'Balsam Poplar'],
  ['Cottonwood Eastern', 'Eastern Cottonwood'],
  ['Aspen Largetooth', 'Large-Tooth Aspen'],
  ['Poplar Lombardy', 'Lombardy Poplar'],
  ['Aspen Trembling', 'Trembling Aspen'],
  ['Cherry Pin', 'Pin Cherry'],
  ['Cherry Black', 'Black Cherry'],
  ['Almond Flowering', 'Flowering Almond'],
  ['Cherry Choke Schubert', 'Choke Schubert Cherry'],
  ['Cherry Choke', 'Choke Cherry'],
  ['Hoptree Common', 'Common Hoptree'],
  ['Oak White', 'White Oak'],
  ['Oak Swamp white', 'Swamp White Oak'],
  ['Oak Bur', 'Bur Oak'],
  ['Oak Pin', 'Pin Oak'],
  ['Oak English', 'English Oak'],
  ['Oak Red', 'Red Oak'],
  ['Sumac Staghorn', 'Staghorn Sumac'],
  ['Locust Black', 'Black Locust'],
  ['Willow Blue Arctic', 'Arctic Willow'],
  ['Willow Weeping', 'Weeping Willow'],
  ['Willow Bebb', 'Bebb Willow'],
  ['Willow Pussy', 'Pussy Willow'],
  ['Willow Corkscrew', 'Corkscrew Willow'],
  ['Willow Black', 'Black Willow'],
  ['Mountain Ash European', 'European Mountain Ash'],
  ['Mountain Ash Showy', 'Showy Mountain Ash'],
  ['Swedish Whitebeam', 'Swedish Whitebeam'],
  ['Lilac Japanese', 'Japanese Lilac'],
  ['Lilac Common', 'Common Lilac'],
  ['Basswood', 'Basswood'],
  ['Linden Littleleaf', 'Littleleaf Linden'],
  ['Elm American', 'American Elm'],
  ['Elm Scotch', 'Scotch Elm'],
  ['Elm Chinese', 'Chinese Elm'],
  ['Elm Siberian', 'Siberian Elm'],
  ['Elm Red', 'Red Elm'],
  ['Elm Rock', 'Rock Elm'],
  ['Cranberry High Bush', 'High Bush Cranberry'],
  ['Larch European', 'European Larch'],
  ['Larch Eastern', 'Eastern Larch'],
  ['Fir Balsam', 'Balsam Fir'],
  ['Fir Colorado', 'Colorado Fir'],
  ['False Cypress Nootka', 'Nootka Cypress'],
  ['Juniper Eastern', 'Eastern Juniper'],
  ['Spruce Norway', 'Norway Spruce'],
  ['Spruce White', 'White Spruce'],
  ['Spruce Black', 'Black Spruce'],
  ['Spruce Serbian', 'Serbian Spruce'],
  ['Spruce Colorado', 'Colorado Spruce'],
  ['Spruce Red', 'Red Spruce'],
  ['Pine Bristlecone', 'Bristlecone Pine'],
  ['Pine Jack', 'Jack Pine'],
  ['Pine Western White', 'Western White Pine'],
  ['Pine Mugo', 'Mugo Pine'],
  ['Pine Black', 'Black Pine'],
  ['Pinyon Parry', 'Parry Pinyon'],
  ['Pine Red', 'Red Pine'],
  ['Pine White', 'White Pine'],
  ['Pine Scotch', 'Scotch Pine'],
  ['Fir Douglas', 'Douglas Fir'],
  ['Yew Canada', 'Canada Yew'],
  ['Cedar Eastern White', 'Eastern White Cedar'],
  // Generalized Species -- Haven't processed below
  ['Elm Prospector', 'Elm Prospector'],
  ['Crabapple Species', 'Crabapple Species'],
  ['Mountain Ash Oakleaf', 'Mountain Ash Oakleaf'],
  ['Pine Species', 'Pine Species'],
  ['Apple Species', 'Apple Species'],
  ['Pine Austrian', 'Pine Austrian'],
  ['Elm Species', 'Elm Species'],
  ['Maple Freeman', 'Maple Freeman'],
  ['Oak Species', 'Oak Species'],
  ['Poplar Species', 'Poplar Species'],
  ['Mountain Ash Species', 'Mountain Ash Species'],
  ['Pear Species', 'Pear Species'],
  ['Cherry Species', 'Cherry Species'],
  ['Ash Species', 'Ash Species'],
  ['Hemlock', 'Hemlock'],
  ['Hawthorn', 'Hawthorn'],
  ['Ironwood', 'Ironwood'],
  ['Juniper', 'Juniper'],
  ['Beech Species', 'Beech Species'],
  ['Maple Species', 'Maple Species'],
  ['Spruce Species', 'Spruce Species'],
  ['Cherry Purple Leaf', 'Cherry Purple Leaf'],
  ['Birch Species', 'Birch Species'],
  ['Birch Weeping', 'Birch Weeping'],
  ['Aspen Columnar', 'Aspen Columnar'],
  ['Elm Pioneer', 'Elm Pioneer'],
  ['Maple Hedge', 'Maple Hedge'],
  ['Walnut Manchurian', 'Walnut Manchurian'],
  ['Dogwood Alternate-Leaved', 'Dogwood Alternate-Leaved'],
  ['Willow False Mountain', 'Willow False Mountain'],
  ['Willow Laurel', 'Willow Laurel'],
  ['Plum species', 'Plum species']
])
